import { useState } from "react";
import { useMutation, useQueries, useQuery } from "@tanstack/react-query";
import { ViewerShell } from "@/components/layouts/ViewerShell";
import { useAuth } from "@/features/auth/hooks/useAuth";
import { getStudent } from "@/services/firestore/students";
import { listAssignmentsByClass, listSubmissionsByStudents, submitAssignment } from "@/services/firestore/assignments";
import type { AssignmentDoc } from "@/types/academic";

export default function ViewerAssignmentsPage() { const { userDoc } = useAuth(); const studentIds = userDoc?.studentIds ?? []; const studentQueries = useQueries({ queries: studentIds.map((id) => ({ queryKey: ["student", id], queryFn: () => getStudent(id) })) }); const classIds = [...new Set(studentQueries.flatMap((item) => item.data?.currentClassIds ?? []))]; const assignmentQueries = useQueries({ queries: classIds.map((id) => ({ queryKey: ["viewer-assignments", id], queryFn: () => listAssignmentsByClass(id) })) }); const assignments = assignmentQueries.flatMap((item) => item.data ?? []); const submissions = useQuery({ queryKey: ["viewer-submissions", studentIds], queryFn: () => listSubmissionsByStudents(studentIds), enabled: studentIds.length > 0 }); return <ViewerShell><h1>Bai tap</h1><div className="mt-4 space-y-3">{assignments.map((item) => <ViewerAssignment key={item.id} assignment={item} studentId={studentIds.find((id) => studentQueries.find((query) => query.data?.id === id)?.data?.currentClassIds.includes(item.classId)) ?? studentIds[0]} saved={submissions.data?.find((value) => value.assignmentId === item.id)}/>)}</div></ViewerShell>; }
function ViewerAssignment({ assignment, studentId, saved }: { assignment: AssignmentDoc & { id: string }; studentId: string; saved?: Awaited<ReturnType<typeof listSubmissionsByStudents>>[number] }) { const [text, setText] = useState(saved?.submissionText ?? ""); const [url, setUrl] = useState(saved?.submissionUrl ?? ""); const mutation = useMutation({ mutationFn: () => submitAssignment(assignment, studentId, { submissionText: text, submissionUrl: url, studentNote: "" }) }); return <article className="border-b border-neutral-200 py-4"><h2>{assignment.title}</h2><p className="mt-1 text-sm text-neutral-600">{assignment.description}</p><textarea placeholder="Noi dung bai lam" value={text} onChange={(e) => setText(e.target.value)} className="mt-3 min-h-24 w-full rounded-input border p-3 text-sm"/><input placeholder="Hoac link bai lam" value={url} onChange={(e) => setUrl(e.target.value)} className="mt-2 min-h-touch w-full rounded-input border px-3 text-sm"/><button onClick={() => mutation.mutate()} className="mt-2 min-h-touch rounded-input bg-primary-500 px-4 text-sm text-white">Nop bai</button>{saved && <p className="mt-2 text-xs text-neutral-500">Trang thai: {saved.status}{saved.score != null ? ` · ${saved.score}/${assignment.maxScore}` : ""} {saved.teacherComment}</p>}</article>; }
