import{addDoc,collection,doc,getDocs,limit,orderBy,query,QueryDocumentSnapshot,serverTimestamp,Timestamp,where,writeBatch,startAfter}from"firebase/firestore";import{db}from"@/services/firebase/client";import{COLLECTIONS}from"@/constants/collections";import{createInvoiceCode,createPaymentContent}from"@/utils/payment";import type{InvoiceDoc,PaymentDoc,PaymentStatus}from"@/types/academic";
import{stableDocumentId}from"@/utils/idempotency";
export async function createInvoice(input:{studentId:string;courseId:string|null;title:string;amount:number;dueAt:Date;bankBin:string;accountNumber:string;accountName:string;actorUid:string}):Promise<void>{const invoiceCode=createInvoiceCode(input.studentId);await addDoc(collection(db,COLLECTIONS.INVOICES),{...input,invoiceCode,paymentContent:createPaymentContent(invoiceCode),dueAt:Timestamp.fromDate(input.dueAt),status:"unpaid",createdBy:input.actorUid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});}
export async function listInvoices():Promise<(InvoiceDoc&{id:string})[]>{const snap=await getDocs(query(collection(db,COLLECTIONS.INVOICES),limit(300)));return snap.docs.map(i=>({id:i.id,...(i.data()as InvoiceDoc)}));}
export interface InvoicePage{items:(InvoiceDoc&{id:string})[];nextCursor:QueryDocumentSnapshot|undefined;}
export async function listInvoicesPage(pageSize=50,cursor?:QueryDocumentSnapshot):Promise<InvoicePage>{const constraints=cursor?[orderBy("createdAt","desc"),startAfter(cursor),limit(pageSize)]:[orderBy("createdAt","desc"),limit(pageSize)];const snap=await getDocs(query(collection(db,COLLECTIONS.INVOICES),...constraints));return{items:snap.docs.map(i=>({id:i.id,...(i.data()as InvoiceDoc)})),nextCursor:snap.docs.length?snap.docs[snap.docs.length-1]:undefined};}
export async function listInvoicesByStudents(ids:string[]):Promise<(InvoiceDoc&{id:string})[]>{const groups=await Promise.all(ids.map(async studentId=>{const snap=await getDocs(query(collection(db,COLLECTIONS.INVOICES),where("studentId","==",studentId),limit(100)));return snap.docs.map(i=>({id:i.id,...(i.data()as InvoiceDoc)}));}));return groups.flat();}
export async function reportPayment(invoice:InvoiceDoc&{id:string},uid:string,reference:string,note:string):Promise<void>{const batch=writeBatch(db);const payment=doc(db,COLLECTIONS.PAYMENTS,stableDocumentId([invoice.id,uid]));batch.set(payment,{invoiceId:invoice.id,studentId:invoice.studentId,amount:invoice.amount,transactionReference:reference,note,status:"reported",reportedBy:uid,verifiedBy:null,reportedAt:serverTimestamp(),verifiedAt:null,updatedAt:serverTimestamp()},{merge:true});batch.update(doc(db,COLLECTIONS.INVOICES,invoice.id),{status:"pending",updatedAt:serverTimestamp()});await batch.commit();}
export async function listPayments():Promise<(PaymentDoc&{id:string})[]>{const snap=await getDocs(query(collection(db,COLLECTIONS.PAYMENTS),limit(300)));return snap.docs.map(i=>({id:i.id,...(i.data()as PaymentDoc)}));}
export async function reconcilePayment(payment:PaymentDoc&{id:string},status:Exclude<PaymentStatus,"reported">,uid:string):Promise<void>{const batch=writeBatch(db);batch.update(doc(db,COLLECTIONS.PAYMENTS,payment.id),{status,verifiedBy:uid,verifiedAt:serverTimestamp(),updatedAt:serverTimestamp()});batch.update(doc(db,COLLECTIONS.INVOICES,payment.invoiceId),{status:status==="verified"?"paid":"rejected",updatedAt:serverTimestamp()});await batch.commit();}
