import { decodeProtectedHeader, importPKCS8, importX509, jwtVerify, SignJWT } from "jose";

export interface Env { FIREBASE_PROJECT_ID:string;FIREBASE_CLIENT_EMAIL:string;FIREBASE_PRIVATE_KEY:string;META_PAGE_ACCESS_TOKEN:string;META_APP_SECRET:string;META_WEBHOOK_VERIFY_TOKEN:string;META_GRAPH_VERSION:string;ALLOWED_ORIGIN:string; }
interface FirebaseClaims { sub:string;user_id?:string;email?:string; }
export interface SendBody { recipientPsid?:string;text:string;type?:string;studentId?:string;tag?:string; }
interface PostBody { message:string;link?:string; }

export function corsHeaders(env:Env){return{"access-control-allow-origin":env.ALLOWED_ORIGIN,"access-control-allow-headers":"authorization, content-type","access-control-allow-methods":"GET,POST,OPTIONS","content-type":"application/json"};}
export function extractBearer(value:string|null):string|null{return value?.match(/^Bearer\s+(.+)$/i)?.[1]??null;}
export function isMessengerTagShape(value:unknown):value is string{return typeof value==="string"&&/^[A-Z_]{3,64}$/.test(value.trim());}
export function buildMessengerPayload(body:SendBody):Record<string,unknown>{const tag=body.tag?.trim();const payload:Record<string,unknown>={recipient:{id:body.recipientPsid},messaging_type:tag?"MESSAGE_TAG":"RESPONSE",message:{text:body.text}};if(tag)payload.tag=tag;return payload;}
export async function verifyMetaSignature(raw:string,signature:string|null,secret:string):Promise<boolean>{if(!signature?.startsWith("sha256="))return false;const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const digest=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(raw));const expected="sha256="+[...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,"0")).join("");if(expected.length!==signature.length)return false;let diff=0;for(let i=0;i<expected.length;i++)diff|=expected.charCodeAt(i)^signature.charCodeAt(i);return diff===0;}
export function extractReferralLinks(payload:unknown):Array<{uid:string;psid:string;pageId:string}>{const result:Array<{uid:string;psid:string;pageId:string}>=[];if(!payload||typeof payload!=="object")return result;const entries=(payload as {entry?:unknown[]}).entry??[];for(const entry of entries){if(!entry||typeof entry!=="object")continue;for(const event of (entry as {messaging?:unknown[]}).messaging??[]){if(!event||typeof event!=="object")continue;const value=event as {sender?:{id?:string};recipient?:{id?:string};referral?:{ref?:string};postback?:{referral?:{ref?:string}}};const uid=value.referral?.ref??value.postback?.referral?.ref;if(uid&&value.sender?.id&&value.recipient?.id)result.push({uid,psid:value.sender.id,pageId:value.recipient.id});}}return result;}

async function verifyFirebaseToken(token:string,env:Env):Promise<FirebaseClaims>{const header=decodeProtectedHeader(token);if(header.alg!=="RS256"||!header.kid)throw new Error("invalid_token_header");const response=await fetch("https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com");if(!response.ok)throw new Error("firebase_keys_unavailable");const certs=await response.json<Record<string,string>>();const cert=certs[header.kid];if(!cert)throw new Error("unknown_token_key");const key=await importX509(cert,"RS256");const{payload}=await jwtVerify(token,key,{audience:env.FIREBASE_PROJECT_ID,issuer:`https://securetoken.google.com/${env.FIREBASE_PROJECT_ID}`,algorithms:["RS256"]});if(!payload.sub)throw new Error("missing_uid");return payload as unknown as FirebaseClaims;}
function fieldString(doc:unknown,name:string):string|undefined{return(doc as {fields?:Record<string,{stringValue?:string}>})?.fields?.[name]?.stringValue;}
async function requireStaff(uid:string,idToken:string,env:Env):Promise<void>{const response=await fetch(`https://firestore.googleapis.com/v1/projects/${env.FIREBASE_PROJECT_ID}/databases/(default)/documents/users/${uid}`,{headers:{authorization:`Bearer ${idToken}`}});if(!response.ok)throw new Error("profile_unavailable");const profile=await response.json();if(fieldString(profile,"status")!=="active"||!["admin","teacher"].includes(fieldString(profile,"role")??""))throw new Error("staff_required");}
async function serviceAccessToken(env:Env):Promise<string>{const key=await importPKCS8(env.FIREBASE_PRIVATE_KEY.replace(/\\n/g,"\n"),"RS256");const assertion=await new SignJWT({scope:"https://www.googleapis.com/auth/datastore"}).setProtectedHeader({alg:"RS256",typ:"JWT"}).setIssuer(env.FIREBASE_CLIENT_EMAIL).setSubject(env.FIREBASE_CLIENT_EMAIL).setAudience("https://oauth2.googleapis.com/token").setIssuedAt().setExpirationTime("1h").sign(key);const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion})});if(!response.ok)throw new Error("service_auth_failed");return String((await response.json<{access_token:string}>()).access_token);}
function fieldStringArray(doc:unknown,name:string):string[]{const values=(doc as {fields?:Record<string,{arrayValue?:{values?:{stringValue?:string}[]}}>})?.fields?.[name]?.arrayValue?.values??[];return values.map(v=>v.stringValue).filter((v):v is string=>Boolean(v));}
async function readServiceDoc(collection:string,id:string,token:string,env:Env):Promise<unknown|null>{const response=await fetch(`https://firestore.googleapis.com/v1/projects/${env.FIREBASE_PROJECT_ID}/databases/(default)/documents/${collection}/${id}`,{headers:{authorization:`Bearer ${token}`}});if(!response.ok)return null;return response.json();}
async function resolveParentPsids(studentId:string,env:Env):Promise<string[]>{const token=await serviceAccessToken(env);const student=await readServiceDoc("students",studentId,token,env);if(!student)return [];const psids:string[]=[];for(const uid of fieldStringArray(student,"parentUids")){const conn=await readServiceDoc("messenger_connections",uid,token,env);const psid=fieldString(conn,"facebookPsid");if(psid&&fieldString(conn,"status")==="active")psids.push(psid);}return psids;}
function firestoreFields(value:Record<string,unknown>):Record<string,unknown>{return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,item===null?{nullValue:null}:typeof item==="string"?{stringValue:item}:typeof item==="boolean"?{booleanValue:item}:typeof item==="number"?{integerValue:String(item)}:{stringValue:JSON.stringify(item)}]));}
async function writeServiceDocument(collection:string,id:string,data:Record<string,unknown>,env:Env):Promise<void>{const token=await serviceAccessToken(env);const response=await fetch(`https://firestore.googleapis.com/v1/projects/${env.FIREBASE_PROJECT_ID}/databases/(default)/documents/${collection}/${id}`,{method:"PATCH",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({fields:firestoreFields(data)})});if(!response.ok)throw new Error("firestore_write_failed");}
async function logOutbox(id:string,data:Record<string,unknown>,idToken:string,env:Env):Promise<void>{await fetch(`https://firestore.googleapis.com/v1/projects/${env.FIREBASE_PROJECT_ID}/databases/(default)/documents/message_outbox/${id}`,{method:"PATCH",headers:{authorization:`Bearer ${idToken}`,"content-type":"application/json"},body:JSON.stringify({fields:firestoreFields(data)})});}
async function sendGraph(body:SendBody,env:Env):Promise<{message_id?:string;recipient_id?:string}>{const url=`https://graph.facebook.com/${env.META_GRAPH_VERSION}/me/messages?access_token=${encodeURIComponent(env.META_PAGE_ACCESS_TOKEN)}`;const request=()=>fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(buildMessengerPayload(body))});let response=await request();if(response.status>=500)response=await request();const data=await response.json<Record<string,unknown>>();if(!response.ok)throw new Error(`meta_${String(data.error??response.status)}`);return data;}
async function handleSend(request:Request,env:Env):Promise<Response>{const idToken=extractBearer(request.headers.get("authorization"));if(!idToken)return new Response(JSON.stringify({error:"missing_bearer_token"}),{status:401,headers:corsHeaders(env)});const claims=await verifyFirebaseToken(idToken,env);await requireStaff(claims.sub,idToken,env);const body=await request.json<SendBody>();if(!body.text?.trim()||body.text.length>2000)return new Response(JSON.stringify({error:"invalid_message"}),{status:400,headers:corsHeaders(env)});const tag=body.tag?.trim();if(body.tag!==undefined&&!isMessengerTagShape(body.tag))return new Response(JSON.stringify({error:"invalid_message_tag"}),{status:400,headers:corsHeaders(env)});let recipients=body.recipientPsid?[body.recipientPsid]:[];if(recipients.length===0&&body.studentId)recipients=await resolveParentPsids(body.studentId,env);if(recipients.length===0)return new Response(JSON.stringify({error:"no_recipient"}),{status:400,headers:corsHeaders(env)});const results:{id:string;recipientPsid:string;status:"sent"|"failed";error?:string}[]=[];for(const psid of recipients){const id=crypto.randomUUID();try{const result=await sendGraph({...body,recipientPsid:psid,tag},env);await logOutbox(id,{type:body.type??"general",studentId:body.studentId??null,recipientPsid:psid,content:body.text,status:"sent",messageTag:tag??null,metaMessageId:result.message_id??null,actorUid:claims.sub,createdAt:new Date().toISOString()},idToken,env);results.push({id,recipientPsid:psid,status:"sent"});}catch(error){await logOutbox(id,{type:body.type??"general",studentId:body.studentId??null,recipientPsid:psid,content:body.text,status:"failed",messageTag:tag??null,error:String(error),actorUid:claims.sub,createdAt:new Date().toISOString()},idToken,env);results.push({id,recipientPsid:psid,status:"failed",error:String(error)});}}const sent=results.filter(r=>r.status==="sent").length;return new Response(JSON.stringify({id:results[0].id,status:sent>0?"sent":"failed",sent,total:results.length,results,error:sent>0?undefined:results[0].error}),{status:sent>0?200:502,headers:corsHeaders(env)});}
async function postGraph(body:PostBody,env:Env):Promise<{id?:string}>{const url=`https://graph.facebook.com/${env.META_GRAPH_VERSION}/me/feed?access_token=${encodeURIComponent(env.META_PAGE_ACCESS_TOKEN)}`;const payload:Record<string,string>={message:body.message};if(body.link)payload.link=body.link;const request=()=>fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});let response=await request();if(response.status>=500)response=await request();const data=await response.json<Record<string,unknown>>();if(!response.ok)throw new Error(`meta_${String(data.error??response.status)}`);return data as {id?:string};}
async function handlePost(request:Request,env:Env):Promise<Response>{const idToken=extractBearer(request.headers.get("authorization"));if(!idToken)return new Response(JSON.stringify({error:"missing_bearer_token"}),{status:401,headers:corsHeaders(env)});const claims=await verifyFirebaseToken(idToken,env);await requireStaff(claims.sub,idToken,env);const body=await request.json<PostBody>();if(!body.message?.trim()||body.message.length>5000)return new Response(JSON.stringify({error:"invalid_post"}),{status:400,headers:corsHeaders(env)});const id=crypto.randomUUID();try{const result=await postGraph(body,env);await logOutbox(id,{type:"page_post",studentId:null,recipientPsid:"page",content:body.message,status:"sent",metaMessageId:result.id??null,actorUid:claims.sub,createdAt:new Date().toISOString()},idToken,env);return new Response(JSON.stringify({id,status:"sent",postId:result.id}),{headers:corsHeaders(env)});}catch(error){await logOutbox(id,{type:"page_post",studentId:null,recipientPsid:"page",content:body.message,status:"failed",error:String(error),actorUid:claims.sub,createdAt:new Date().toISOString()},idToken,env);return new Response(JSON.stringify({id,status:"failed",error:String(error)}),{status:502,headers:corsHeaders(env)});}}
async function handleWebhook(request:Request,env:Env):Promise<Response>{if(request.method==="GET"){const url=new URL(request.url);if(url.searchParams.get("hub.mode")==="subscribe"&&url.searchParams.get("hub.verify_token")===env.META_WEBHOOK_VERIFY_TOKEN)return new Response(url.searchParams.get("hub.challenge")??"");return new Response("Forbidden",{status:403});}const raw=await request.text();if(!await verifyMetaSignature(raw,request.headers.get("x-hub-signature-256"),env.META_APP_SECRET))return new Response("Invalid signature",{status:401});for(const link of extractReferralLinks(JSON.parse(raw)))await writeServiceDocument("messenger_connections",link.uid,{uid:link.uid,facebookPsid:link.psid,pageId:link.pageId,status:"active",linkedAt:new Date().toISOString()},env);return new Response("EVENT_RECEIVED");}
export default{async fetch(request:Request,env:Env):Promise<Response>{if(request.method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders(env)});const path=new URL(request.url).pathname;try{if(path==="/health")return new Response(JSON.stringify({ok:true}),{headers:corsHeaders(env)});if(path==="/api/messenger/send"&&request.method==="POST")return handleSend(request,env);if(path==="/api/messenger/post"&&request.method==="POST")return handlePost(request,env);if(path==="/webhook")return handleWebhook(request,env);return new Response("Not found",{status:404});}catch(error){return new Response(JSON.stringify({error:String(error)}),{status:500,headers:corsHeaders(env)});}}};
